# html languages
language:
- zh-CN
- en

# aloha has different themes, default one is simple,
# you could change it with simple, xx
theme: simple

# main menu navigation
# icon name see http://semantic-ui.com/elements/icon.html
menu:
  Home:
    name: homePage
    value: /index.html
    icon: home
#  Rss:
#    name: rss
#    value: /atom.xml
#    icon: rss
#  About:
#    name: aboutPage
#    value: /about
#    icon:

# some configuration about index page
index:
  showyear: false

# Miscelaneous
favicon: /favicon.ico

# configure cdn source, in order to access faster
# default is //cdn.bootcss.com/
# if you deploy in China, I suggest you use //cdn.bootcss.com/
# start with // means it could auto to adapt to http or https
# maybe source url is different between multiple cdn services, ATTENTION please!
cdn: //cdn.bootcss.com

# stylesheets loaded in the <head>
stylesheets:
- local/css/aloha.css
#- local/css/semantic-ui/2.2.4/semantic.min.css
- cdn/semantic-ui/2.2.4/semantic.min.css
- cdn/magnific-popup.js/1.1.0/magnific-popup.min.css

# scripts loaded in the end of the body
scripts:
- cdn/jquery/3.1.0/jquery.min.js
- cdn/semantic-ui/2.2.4/semantic.min.js
- cdn/algoliasearch/3.18.1/algoliasearch.min.js
- cdn/algoliasearch-helper-js/2.13.0/algoliasearch.helper.min.js
#- cdn/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js
- local/js/semantic-ui-algolia.js
- local/js/aloha-events.js